# Generated by Django 5.2.8 on 2025-12-12 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_muscle_group'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinplan',
            name='reps',
            field=models.CharField(default='10-12', max_length=20),
        ),
        migrations.AlterField(
            model_name='exerciseinplan',
            name='rest_time',
            field=models.CharField(default='60s', max_length=20),
        ),
        migrations.AlterField(
            model_name='exerciseinplan',
            name='sets',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('training_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.trainingday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('reps_done', models.IntegerField()),
                ('weight_kg', models.FloatField(default=0.0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plans.workoutsession')),
            ],
        ),
    ]
