# Generated by Django 5.2.8 on 2025-12-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_exerciseinplan_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='custom_name',
            field=models.CharField(blank=True, default='My Workout', max_length=100),
        ),
    ]
