# Generated by Django 5.2.8 on 2025-12-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('LEGS', 'Legs'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('FOREARMS', 'Forearms'), ('CORE', 'Core'), ('FULLBODY', 'Full Body')], max_length=20),
        ),
    ]
